### ISSUE TITLE
1.04.1的JasonHandwriting3不能安裝不同字重

### ISSUE THREAD

**Issue by jeffchang-git** [max32002/JasonHandWritingFonts#1]
1.04.1的JasonHandwriting3安裝中出現 已安裝 要取代嗎 的訊息
選擇是或否，最後只能出現一種字重

OS：WIN7

**Comment by max32002** [comment]
已解決，請下載 JasonHandwriting3 ver 1.22.2, 修正不能安裝不同字重的問題.
